<a href="https://colab.research.google.com/github/Nautyy9/getting_started_with_tensorflow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Tensors are multi-dimensional array


In [ ]:
zero_d_arr = tf.constant(8)

In [ ]:
one_d_arr = tf.constant(
    [1,24,34],
    )

In [ ]:
two_d_arr = tf.constant(
    [
      [1,24,34], [3,45,6],
    ], dtype="float32"
    )
print(two_d_arr)

tf.Tensor(
[[ 1. 24. 34.]
 [ 3. 45.  6.]], shape=(2, 3), dtype=float32)


In [ ]:
three_d_arr = tf.constant(
    [
      [
          [1,24,34], [3,45,6],
      ],
      [
          [324,32235,3432], [1234,345,356],
      ],
    ]
    )


In [ ]:
four_d_arr = tf.constant(
    [
      [
        [
            [1,24,34], [3,45,6]
        ],
        [
            [324,32235,3432], [1234,345,356]
        ],
      ],
      [
        [
            [1423,32424,34234], [13,245,46]
        ],
        [
            [34,3235,432], [234,35,36],
        ],
      ],
    ]
)


# From Numpy Array to Tensorflow Tensor

In [ ]:
import numpy as np

np_array = np.array([3,1,3,5], dtype="int32")


# takes in numpy array as the arguement
np_to_tensor = tf.convert_to_tensor(np_array)
print(np_to_tensor)

tf.Tensor([3 1 3 5], shape=(4,), dtype=int32)



# Some New Numpy Methods


In [ ]:
import numpy as np
np_2d_array_1  = np.array([
    [2,3,4],
    [1,5,2],
    ])
np_2d_array_2  = np.array([
    [4,7],
    [12,10],
    [5,13]
])

np_2d_array_trans  = np.array([
    [2,3,4],
    [1,5,2],
    [1,6,4]
    ])
np_einsum_matmul = np.einsum("ij,jk -> ik", np_2d_array_1,  np_2d_array_2)
np_einsum_mul = np.einsum("ij , ji -> ij", np_2d_array_1,  np_2d_array_2)
np_einsum_sum_all = np.einsum("ij,ji -> ", np_2d_array_1,  np_2d_array_2)
np_einsum_sum_col = np.einsum("ij -> j",  np_2d_array_2)
np_einsum_sum_row = np.einsum("ij -> i ", np_2d_array_1)
np_einsum_trans = np.einsum("ij -> ji" , np_2d_array_trans)
print(np_einsum_trans)


[[2 1 1]
 [3 5 6]
 [4 2 4]]


# TENSORFLOW METHODS


# Cast
*   create a new dtype for existing tensor





In [ ]:
cast_tensor = tf.cast(one_d_arr, dtype = tf.dtypes.int16)
print(cast_tensor)

tf.Tensor([ 1 24 34], shape=(3,), dtype=int16)


# EYE
* Construct an identity matrix, or a batch of matrices.
* eye is tf method (tf.eye) that create identity matrix

In [ ]:
# the batch_shape defines the batch size , i,e when shape is (3,2,2) then batch is 3 having 2 rows and 2 cols
# in 4D tensor (4,3,2,2) batch size is 4,3 rows->2, cols ->2 the batch defines the outer dimensions beside the rows and columns
# batch_size = [3,] then the shape is (3,rows, cols)
# batch_size = [4,3] then the shape is (4,3 , rows, cols)
tf_iden_no_batch = tf.eye(
    num_rows=3,
    num_columns= None,
    batch_shape=None,
    dtype="int32",
    name=None
)

tf_iden_wt_batch3 = tf.eye(
    num_rows=5,
    num_columns= None,
    batch_shape= [3,],
    dtype="int32",
    name=None
)

tf_iden_wt_batch43 = tf.eye(
    num_rows=5,
    num_columns= None,
    batch_shape= [4,3],
    dtype="int32",
    name=None
)

print(tf_iden_wt_batch43)

# FILL


*   Create a tensor filled with scalar values with a defined(given) shape
* it take a shape as an array(1D tensor) and tensor fill each value with the specified arguement




In [ ]:
tf_fill = tf.fill([2,3,4], 9)
print(tf_fill)

tf.Tensor(
[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]], shape=(2, 3, 4), dtype=int32)


# ONES , ONES_lIKE , ZEROS , ZEROS_LIKE

*   ones will create a tensor with all 1, ones_like create all 1(values) tensor with taking the  shape of another tensor.
*   zeros will create a tensor with all 0, zero_like create all 0(values) tensor with taking the  shape of another tensor

**dtype -> float default**

In [ ]:
tf_ones = tf.ones([1,2,4], dtype="int32")
tf_zeros = tf.zeros([1,2,4], dtype="int32")

# will take the shape as well as the type from the arguement tensor
tf_ones_like = tf.ones_like(tf_ones)
tf_zeros_like = tf.zeros_like(tf_zeros)


print(tf_ones, tf_zeros, tf_ones_like, tf_zeros_like)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]]], shape=(1, 2, 4), dtype=int32) tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]]], shape=(1, 2, 4), dtype=int32) tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]]], shape=(1, 2, 4), dtype=int32) tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]]], shape=(1, 2, 4), dtype=int32)


# SHAPE , RANK , SIZE
* shape gives the shape with the type(i.e, if its a tensorflow tensor or not) of specified tensor
* rank gives the dimension of the specified tensor
* size returns the no. of element in the tensor

In [ ]:
print(tf.shape(tf_ones_like))
print(tf.rank(tf_zeros_like))
print(tf.size(tf_ones))

tf.Tensor([1 2 4], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


# RANDOM

**CREATE A TENSORS WITH RANDOM VALUES**
# `RANDOM-NORMAL`
# `RANDOM-UNIFORM`

* normal creates a tensor with random values with normal distribution(Mean, Standard Deviation)

* uniform creates a tensor with random values with uniform distribution (a=minval, b=maxval)


In [ ]:
# normal signifies the normal distribution i.e having mean and std.dev
# <-- It may not contain int type -->
tf_random_normal = tf.random.normal(
    [2,3],
    mean=100,
    stddev=1,
    seed=None,
    dtype=tf.dtypes.float32,
)
# print(tf_random_normal)


tf_random_uniform = tf.random.uniform(
    [2,3],
    minval=1,
    maxval=10,
    dtype= tf.dtypes.float32,
    seed=None,
    name=None
)
# print(tf_random_uniform)





# SEEDING
# seeding is done to create replica of the existing tensor or tensor's
"""

* seeding require a global set_seed and local seed(parameter to tf.random)
* the global seed value of one matches the global seed value of another i.e
  tf.random.set_seed(5) == tf.random.set_seed(5)
* once the global seed got matched then we match individual tensor with their individual seed value i.e irrespective of the position of the tensor if the  see value is same
then it will get the same value

"""


tf.random.set_seed(10)
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=5))
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=5))
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=1))
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=1))

# since we've 2 values for one seed i.e 2 tensors for seed=5 and another 2 tensors for seed=1, now each seed has 2 values hence at reasigning one of the two values is assigned

tf.random.set_seed(10)
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=1))
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=1))
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=5))
print(tf.random.uniform(shape=[1,2,3] , minval=10, maxval=100, seed=5))


tf.Tensor(
[[[99.049736 43.170063 20.454672]
  [87.64169  52.827614 51.136803]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[94.997284 96.20311  28.39783 ]
  [80.996826 77.8827   70.30328 ]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[98.84572  97.43886  76.15645 ]
  [65.48087  26.866224 54.283913]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[56.9203   27.7251   33.827168]
  [44.04045  38.15204  92.92371 ]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[98.84572  97.43886  76.15645 ]
  [65.48087  26.866224 54.283913]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[56.9203   27.7251   33.827168]
  [44.04045  38.15204  92.92371 ]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[99.049736 43.170063 20.454672]
  [87.64169  52.827614 51.136803]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[94.997284 96.20311  28.39783 ]
  [80.996826 77.8827   70.30328 ]]], shape=(1, 2, 3), dtype=float32)


#

# MATH
**TensorFlow provides a variety of math functions**

`MATH.ABS`
tf-math-abs-TensorFlow-v2-12-0.png

`MATH.ADD`
`MATH.MULTIPLY`
`MATH.DIVIDE`
`MATH.SUBTRACT`
`MATH.MAXIMUM`
`MATH.MINIMUM`
`MATH.POW`
`MATH.ROUND`
`MATH.SQRT`
`e.t.c`





In [ ]:
abs_tensor = tf.constant([[1,-2,3,-4,-5], [-6,-7,8,-9,-10]], dtype="int32")

a_tensor = tf.constant([[1.9,2,3,4,5], [6,7,8,9,10]], dtype=tf.dtypes.float32)
b_tensor = tf.constant([[10.1,11,12,13,14.9], [15,16, 17,18,19]], dtype=tf.dtypes.float32)

complex_tensor = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
# b_tensor = tf.constant([[7]], dtype="int32") # this is called BROADCASTING where only one element act as all i.e, [7] = [[7,7,7,7,7],[7,7,7,7,7]]

tf_math_mul = tf.math.multiply(a_tensor, b_tensor)
tf_math_add = tf.math.add(a_tensor, b_tensor)
tf_math_divide = tf.math.divide(a_tensor, b_tensor) # return infinite if denominator is zero
tf_math_divide_no_nan = tf.math.divide_no_nan(a_tensor, b_tensor) # return  0 if denominator is zero , compatible types are float32, float64
tf_math_subtract = tf.math.subtract(a_tensor, b_tensor)
tf_math_abs = tf.math.abs(a_tensor) # return all positive value
tf_math_abs_complex = tf.math.abs(complex_tensor)
tf_math_max = tf.math.maximum(a_tensor,b_tensor)
tf_math_min = tf.math.minimum(a_tensor,b_tensor)
tf_math_pow = tf.math.pow(a_tensor, 2)
tf_math_round = tf.math.round(a_tensor)
tf_math_sqrt = tf.math.sqrt(a_tensor)
tf_math_argmax = tf.math.argmax(a_tensor)
tf_math_reduce_sum= tf.math.reduce_sum(a_tensor , axis=None , keepdims=True, name=None)
tf_math_top_k = tf.math.top_k(a_tensor, k=2)

# print(tf_math_abs_complex)

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5.,  4.],
       [10.,  9.]], dtype=float32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [4, 3]], dtype=int32)>)




#**LINEAR ALGEBRA**

`provides collections of linear algerbra operation for tensors`



**1. BAND PART**
---
Copy a tensor setting everything outside a central band in each innermost matrix to zero.


\**CONDITION ->  (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper)**


---


* in this we provide input tensor with a following lower and upper values if the
band_part condition satifies then the value is retained else 0 is returned in new o/p matrix



*  in this tensor the value returned are m-n (row-column)
 * input_tensor_for_band_m_n = tf.constant([
    [ 0,  -1,  -2],
    [1,  0,  -1],
    [2, 1,  0],
    [3, 2, 1],
]
)

* here n-m (cols -rows)
  * input_tensor_for_band_n_m = tf.constant([
    [ 0,  1,  2],
    [-1,  0,  1],
    [-2, -1,  0],
    [-3, -2, -1],
]
)






In [ ]:
# m-n and n-m are important to check condition on every value and if it specify that then return the corresponding value

tf_input_tensor = tf.random.uniform(shape=(3,3), minval=5 , maxval=20 , dtype=tf.dtypes.int32)
# print(tf_input_tensor)


tf_band_part = tf.linalg.band_part(tf_input_tensor, 0, 2)
print(tf_band_part)


tf.Tensor(
[[18  8  5]
 [ 0 13 19]
 [ 0  0 13]], shape=(3, 3), dtype=int32)


 **2. INVERSE**
 ---
* Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).
* work only for float32/64



In [ ]:
tf_cast = tf.cast(tf_input_tensor, dtype=tf.dtypes.float32)

tf_inv = tf.linalg.inv(tf_cast)
print(tf_inv)

tf.Tensor(
[[ 0.06689868  0.00541376 -0.03364269]
 [ 0.00154679 -0.07501933  0.10904872]
 [-0.04331014  0.10054138 -0.05336427]], shape=(3, 3), dtype=float32)


In [ ]:
tf_tens1 = tf.random.uniform(shape=(3,3), minval=5 , maxval=20 , dtype=tf.dtypes.int32)
tf_tens2 = tf.random.uniform(shape=(3,3), minval=5 , maxval=20 , dtype=tf.dtypes.int32)

tf_matmul = tf.linalg.matmul(tf_tens1, tf_tens2)
print(tf_matmul)

tf.Tensor(
[[454 436 410]
 [506 327 325]
 [283 255 242]], shape=(3, 3), dtype=int32)


#**EXPAND DIMENSIONS, SQUEEZE**
* expand_dims is used to increase the dimensions of the tensor , by inserting 1 at specified position using [ axis ] parameter
  * axis refer to index i.e, axis=0 will add 1 to start and so on...
  * it convert low dimension array to high dimension array i.e, shape(4,5) -> axis=0 -> (1,4,5) , axis=1->(4,1,5), axis=2->(4,5,1), axis=3-> !!error

* opposite of expand is squeeze
  * removes the axis with dim = 1 (length=1)

In [ ]:

tf_1 = tf.random.uniform(shape=([3,3]), minval=5 , maxval=20 , dtype=tf.dtypes.int32)

exp_dim = tf.expand_dims(tf_1, axis=0)

squeeze_dim = tf.squeeze(exp_dim) # if axis specied then remove only one dim of len 1 else remove all
print(exp_dim, squeeze_dim)





tf.Tensor(
[[[10  9 12]
  [13  5  9]
  [13 15 19]]], shape=(1, 3, 3), dtype=int32) tf.Tensor(
[[10  9 12]
 [13  5  9]
 [13 15 19]], shape=(3, 3), dtype=int32)


# CONCAT
* concat tensors along one direction defined by axis

In [ ]:
tf_1 = tf.random.uniform(shape=(3,3), minval=5 , maxval=20 , dtype=tf.dtypes.int32)
tf_2 = tf.random.uniform(shape=(3,3), minval=5 , maxval=20 , dtype=tf.dtypes.int32)

# the tensors must need to be passed in as arrays
tf_concat_row = tf.concat([tf_1, tf_2], axis=0)#0 means the whole row would to attached to
tf_concat_into_cols = tf.concat([tf_1, tf_2], axis=1)#0 since the row cannot be attaced to col directly i.e [1,2,3,4,5] ->we've to transpose it and  then attach to the row


print('\n', tf_1, tf_2)
print('\n',tf_concat_row, tf_concat_into_cols)




 tf.Tensor(
[[11  5  9]
 [11 12 16]
 [ 8 17 19]], shape=(3, 3), dtype=int32) tf.Tensor(
[[13  5 16]
 [19 12  9]
 [ 7 14 11]], shape=(3, 3), dtype=int32)

 tf.Tensor(
[[11  5  9]
 [11 12 16]
 [ 8 17 19]
 [13  5 16]
 [19 12  9]
 [ 7 14 11]], shape=(6, 3), dtype=int32) tf.Tensor(
[[11  5  9 13  5 16]
 [11 12 16 19 12  9]
 [ 8 17 19  7 14 11]], shape=(3, 6), dtype=int32)


# STACK

* Stacks a list of rank-R tensors into one rank-(R+1) tensor.
* tf.stack(
    values, axis=0, name='stack'
)

In [ ]:
tf_1 = tf.random.uniform(shape=(3,4), minval=5 , maxval=30 , dtype=tf.dtypes.int32)
tf_2 = tf.random.uniform(shape=(3,4), minval=5 , maxval=30 , dtype=tf.dtypes.int32)

# shape must match
# default axis =0 , placing at first index ,axis=1-> placing at second index and so on...
# now why 2 we get as batch size? since our input values are 2 tensors thef -> output batch = 2 if i/p tensor are 3 then batch = 3
tf_stack = tf.stack([tf_1, tf_2] ,axis=1)
print(tf_stack)


tf.Tensor(
[[[21 23  9 15]
  [13  5 12 20]]

 [[18 27  9 28]
  [ 7 27 13  6]]

 [[ 6 13 29 25]
  [10  6 21 18]]], shape=(3, 2, 4), dtype=int32)
